### PR TITLE
Fix blacklist expiration behavior in BlacklistingConsulFailoverStrategy

### LINKED ISSUE #388: non recoverable state in `withMultipleHostAndPort` when consuls are blacklisted
When using the `withMultipleHostAndPort`, there is a `blacklistTime` duration.  I would expect that the bad host that was blacklisted would be retried after the duration is over, but it is not the case.

```
import com.google.common.net.HostAndPort;

import java.time.Duration;
import java.time.Instant;
import java.util.Arrays;

public class CheckConsul {
    public static void main(String[] args) {
        var consul = Consul.builder().withPing(false).withMultipleHostAndPort(
                        Arrays.asList(
                                HostAndPort.fromString("a.foo.bar.baz:8500"),
                                HostAndPort.fromString("b.foo.bar.baz:8500")
                        ),
                        Duration.ofMillis(2000)
                )
                .build();

        var client = consul.keyValueClient();

        for (int i = 0; i < 10; i++) {
            try {
                var res = client.getValueAsString("foo").orElse("");
                System.out.println(Instant.now() + " Result: " + res);
            } catch (Exception e) {
                System.out.println(Instant.now() + " Error: " + e);
            }
            System.out.println("Sleeping");
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ignored) {
            }
        }
    }
}


2024-12-09T19:23:43.837941Z Error: org.kiwiproject.consul.ConsulException: Unable to successfully determine a viable host for communication.
Sleeping
2024-12-09T19:23:44.846135Z Error: org.kiwiproject.consul.ConsulException: Consul failover strategy has determined that there are no viable hosts remaining.
Sleeping
2024-12-09T19:23:45.851187Z Error: org.kiwiproject.consul.ConsulException: Consul failover strategy has determined that there are no viable hosts remaining.
Sleeping
2024-12-09T19:23:46.855286Z Error: org.kiwiproject.consul.ConsulException: Consul failover strategy has determined that there are no viable hosts remaining.
Sleeping
2024-12-09T19:23:47.861092Z Error: org.kiwiproject.consul.ConsulException: Consul failover strategy has determined that there are no viable hosts remaining.
Sleeping
2024-12-09T19:23:48.866362Z Error: org.kiwiproject.consul.ConsulException: Consul failover strategy has determined that there are no viable hosts remaining.
Sleeping
2024-12-09T19:23:49.871131Z Error: org.kiwiproject.consul.ConsulException: Consul failover strategy has determined that there are no viable hosts remaining.
Sleeping
2024-12-09T19:23:50.878096Z Error: org.kiwiproject.consul.ConsulException: Consul failover strategy has determined that there are no viable hosts remaining.
Sleeping
2024-12-09T19:23:51.884974Z Error: org.kiwiproject.consul.ConsulException: Consul failover strategy has determined that there are no viable hosts remaining.
Sleeping
2024-12-09T19:23:52.893066Z Error: org.kiwiproject.consul.ConsulException: Consul failover strategy has determined that there are no viable hosts remaining.
Sleeping
```

The issue is in https://github.com/kiwiproject/consul-client/blob/v1.4.2/src/main/java/org/kiwiproject/consul/util/failover/ConsulFailoverInterceptor.java#L94 where the viability is checked, but not take into account of the blacklist timeout.  And the resetting of the timeout only happens when inside  `isRequestViable`:
* https://github.com/kiwiproject/consul-client/blob/v1.4.2/src/main/java/org/kiwiproject/consul/util/failover/ConsulFailoverInterceptor.java#L108
* https://github.com/kiwiproject/consul-client/blob/v1.4.2/src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java#L61
* https://github.com/kiwiproject/consul-client/blob/v1.4.2/src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java#L106

### PR DESCRIPTION
**Pull request by sleberknight**
* Factor duplicate logic from if and else branches in computeNextStage.
* Extract blacklist expiration duration logic from findTargetNotInBlacklist to new method isPastBlacklistDuration.
* Change isRequestViable to call findTargetNotInBlacklist. Because findTargetNotInBlacklist will remove a target from the blacklist if past the expiration, this now ensures a correct result. If the target is not blacklisted, then the request is viable. If it or any other target is blacklisted but past the expiration, that target is considered viable and removed from the blacklist. Only if all targets are currently in blacklist and none have expired is the request considered not viable.
* Create addToBlacklist method to replace duplicate blacklist.put calls.
* Create isBlacklisted method to check if a target is in blacklist.
* Create isNotBlacklisted method to check if a target is not in blacklist.
* Rename fromRequest to hostAndPortFromRequest for clarity.
* Rename the blacklistingConsulFailoverStrategy field in the test to just "strategy" since it is much shorter, and because the test is only related to the BlacklistingConsulFailoverStrategy.
* Rename the "current" parameter in ConsulFailoverStrategy methods to "request"
* Add more tests. Move the original tests inside a nested class ComputeNextStage. The new tests are nested inside their own nested classes for the various scenarios. I kept the tests for blacklsit expiration for computeNextStage in a separate nested class, ComputeNextStageExpiration, mainly b/c they are new and are specifically for testing the expiration logic. Also added dedicated tests for isRequest and the (internal) isPastBlacklistDuration method.

Fixes #388

### CODE REVIEW

**Comment by sleberknight** [comment]
@bt-wil Take a look, give it a try, and see if it works as expected now. I combined your ideas with the ones I had originally prototyped. This doesn't address the zero duration since I will do separately.

Specifically, I used your `isPastBlacklistDuration` because it had a better name than mine and simpler code. Also, thanks for catching the duplicate if/else in `computeNextStage`. That definitely simplifies the code.

The only real difference is that I changed `isRequestViable` so that it can also expire targets. It does this by calling `findTargetNotInBlacklist()` and just returning whether the `Optional` is present (when present, the request is viable). I found that without doing this, the `while` loop in `ConsulFailoverInterceptor#intercept` would return `false` when all targets were blacklisted, and therefore not choose another target.

File: src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java [hunk 1]
```diff
@@ -91,43 +82,75 @@ public Optional<Request> computeNextStage(@NonNull Request previousRequest, @Nul
...
+        // value of the target key above. If that happens, just return true. It
+        // won't cause any problems with the Map#remove operation since that
+        // will just return null if there was no mapping with the given key.
+        if (isNull(blacklistedAt)) {
+            return true;
+        }
+
+        // If the duration between the blacklist time ("then") and "now" is greater than the
+        // timeout duration (Duration(then, now) - timeout >= 0), then the timeout has passed
+        var adjustedBlacklistDuration = Duration.between(blacklistedAt, Instant.now()).minusMillis(timeout);
```
Comment (bt-wil) [inline src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java:116]: could be simpler to use before/after
```
return Instant.now().isAfter(blacklistedAt.addMillis(timeout))
```
though it would change the logic slightly since the expiration happens `after` the timeout instead of `at or after`

File: src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java [hunk 2]
```diff
@@ -91,43 +82,75 @@ public Optional<Request> computeNextStage(@NonNull Request previousRequest, @Nul
...
+    }
+
     private static boolean previousResponseFailedAndWasNot404(Response previousResponse) {
         return nonNull(previousResponse) && !previousResponse.isSuccessful() && previousResponse.code() != 404;
     }
 
     @Override
     public boolean isRequestViable(@NonNull Request current) {
-        return (targets.size() > blacklist.size()) || !blacklist.containsKey(fromRequest(current));
+        return findTargetNotInBlacklist().isPresent();
```
Comment (bt-wil) [inline src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java:131]: the check is for the `current` request, but this iterates through the entire `targets`, so the `current` parameter is misleading -- method/signature change?

also, this has a minor performance penalty since it could loop through the list.

File: src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java (hunk 1 above)
Comment (sleberknight) [reply src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java:116]: Yes, I agree that is more understandable.

It's a shame `Instant` does not have `isAfterOrEqualTo`, but to keep the logic the same, how about:

```java
// If "now" is after or equal to the time target was blacklisted plus the timeout amount,
// then the timeout has passed
var timeoutExpiration = blacklistedAt.plusMillis(timeout);
var now = Instant.now();
return now.equals(timeoutExpiration) || now.isAfter(timeoutExpiration);
```

File: src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java (hunk 2 above)
Comment (sleberknight) [reply src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java:131]: Agree that the parameter is misleading based on my reading of the rest of the Javadoc, which says:

> Determines if there is a viable candidate for the next request

And the `@return` description says:

> A boolean representing if there is another possible request candidate available.

So, it seems like this method really is meant to check whether there is _any_ target available to handle it. And so I think the parameter should be changed to just the generic `request`. And also probably for the `markRequestFailed` method as well, for the same reason.

As for the implementation, if you do not check other if targets are available, then once all targets are  in the blacklist, they don't ever come out of it - i.e., the `CheckConsul` program you provided tries `a.foo.bar.baz` and `b.foo.bar.baz` on the first attempt, and after that `ConsulFailoverInterceptor` always throws an exception with the message `"Consul failover strategy has determined that there are no viable hosts remaining"`. 

But I agree maybe we can first do the original checks (are there more targets than in blacklist, or is the current request target not in blacklist) which keeps things faster. And then if those both fail, we tack on the `findTargetNotInBlacklist().isPresent()` check, which may have the side-effect of removing a target from the blacklist. The code becomes:

```java
    @Override
    public boolean isRequestViable(@NonNull Request request) {
        return atLeastOneTargetIsAvailable() ||
                isNotBlacklisted(hostAndPortFromRequest(request)) ||
                findTargetNotInBlacklist().isPresent();
    }

    private boolean atLeastOneTargetIsAvailable() {
        return targets.size() > blacklist.size();
    }
```

Another option would be to use a background thread that periodically executes. It would check whether any targets have passed their expiration time in the blacklist, and remove them. But, even though I don't really love the side-effect in `findTargetNotInBlacklist`, I also don't really think it's worth having a blacklist "pruner" thread. `findTargetNotInBlacklist` is private so outside client code won't be calling it directly.

Comment (bt-wil) [reply src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java:131]: In terms of functionality, it looks fine to me.

What is misleading is the method name `isRequestViable(@NonNull Request ...)` implies checking _the_ request to see if it is viable, instead of _any_ request that is viable.

I'm not quite sure why `isRequestViable` is needed -- can it let `computeNextStage` run until all hosts are exhausted?

> But, even though I don't really love the side-effect in findTargetNotInBlacklist, I also don't really think it's worth having a blacklist "pruner" thread.

Yep, agreed.  The side-effect is unexpected.

Comment (sleberknight) [reply src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java:131]: Happy New Year! 🥳 🎈 

Agree, I don't understand why `isRequestViable` is needed either, but I hesitate to change it since I don't fully understand the code and don't really want to start making major changes as long as things mostly work as expected.

There are two commits where the failover functionality was added:

1. _Add Multiple Host Failover Support To Consul Client_ in ad62d3e817301ae7670b10a13dd0be475dbcd882 on Oct 6, 2018
2. _A 400 series error should not blacklist the consul instance_ in 6cc62c82ac0ebd1ae5e5a112477cbc1651e45209 on Dec 12, 2018

The first commit adds `ConsulFailoverInterceptor`, the `ConsulFailoverStrategy` interface, and the `BlacklistingConsulFailoverStrategy` implementation.

In the first implementation of `ConsulFailoverInterceptor`, the `intercept` method uses the `Response` from calling `Chain#proceed`. Depending on its success, it sets the `previousResponse` and changes the `previousRequest`. So, the `previousResponse` passed into `ConsulFailoverStrategy#compureNextStage` could be non-null.

The second commit removes the `lastResponse` handling. The commit message explains:

> A 400 series error should not blacklist the consul instance that is responding. This is because a 404 or 403 error is actually completely valid.

Unfortunately, the original author did not remove either the (always `null`) `previousResponse` local variable in `ConsulFailoverInterceptor#intercept` or the argument in the `ConsulFailoverStrategy#computeNextStage` method. Since that second commit, the `previousResponse` argument is _always_ null, and the related code in `BlacklistingConsulFailoverStrategy ` is dead code. It's also why I added the comment in code and referenced the investigation task #195, but did not change it since it is part of the public API.

I think it would be safe to remove the `previousResponse` argument from  `ConsulFailoverStrategy#computeNextStage` in the next major version, 2.0.0, which also fixes some other problems flagged by IntelliJ and Sonar.

So for now, I think we'll just make these relatively small changes so that the blacklisting expiration works more or less as expected. I will also add an issue to the 2.0.0 milestone to remove the `previousResponse` argument.

File: src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java (hunk 1 above)
Comment (sleberknight) [reply src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java:116]: Resolving this thread as fixed.

File: src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java (hunk 2 above)
Comment (sleberknight) [reply src/main/java/org/kiwiproject/consul/util/failover/strategy/BlacklistingConsulFailoverStrategy.java:131]: Added the following issues that will deprecate, add a replacement, and eventually remove the `previousResponse` argument:

* #394 
* #395 
* #396
